<?php

$url = (isset($_GET['url']) && $_GET['url'] != "") ? $_GET['url'] : ((isset($_POST['url']) && $_POST['url'] != "") ? $_POST['url'] : NULL);

$name = (isset($_GET['name']) && $_GET['name'] != "") ? $_GET['name'] : ((isset($_POST['name']) && $_POST['name'] != "") ? $_POST['name'] : NULL);

$api = (isset($_GET['api']) && $_GET['api'] != "") ? $_GET['api'] : ((isset($_POST['api']) && $_POST['api'] != "") ? $_POST['api'] : NULL);

$from = (isset($_GET['from']) && $_GET['from'] != "") ? $_GET['from'] : NULL;

include("config.php");
include("function.php");

function createLink($url)
{
	if($url != NULL)
	{
		if(!($hash = urlNotOnBdd($url)))
		{
			if($name == NULL)
			{
				$hash = addUrlBdd($url,$url);
			}
			else
			{
				$hash = addUrlBdd($url,$name);
			}
			return $hash;
		}
		else
		{
			return $hash;	
		}
	}
}



if($from == "bkmk")
{
?>
	var d = document.createElement("div");
	var a = document.createElement("a");
	var s = document.createElement("span");
	<?php
	
	if(substr($url,0,14) == "http://rgls.it")
	{
		?>
		a.setAttribute("href","<?php echo $url; ?>");
		s.innerHTML = 'You are already on <?php echo $SERVER_NAME; ?> : </span>';
		a.innerHTML = "<?php echo $url; ?>";
		<?php
	}
	else
	{
		$link = createLink($url);
	?>
		
		a.setAttribute("href","http://<?php echo $SERVER_URL; ?>/<?php echo $link; ?>");
		s.innerHTML = 'Url generated by <?php echo $SERVER_NAME; ?> : </span>';
		a.innerHTML = "http://<?php echo $SERVER_URL; ?>/<?php echo $link; ?>";
	<?php
	}
	?>
	
	a.setAttribute("target","_blank");
	d.style.position = "fixed";
	d.style.zIndex = "2000";
	d.style.float = "left";
	d.style.width = "100%";
	d.style.height = "30px";
	//d.style.borderRadius = "10px";
	d.style.webkitBoxShadow = "0px 0px 20px RGBA(0,0,0,0.7) ";
	d.style.background = "-webkit-gradient(linear,center top, center bottom, from(#fff), to(#ddd))";
	d.style.top = "-40px";
	d.style.left = "0px";
	d.style.webkitTransition = "top 0.7s ease-out";
	
	
	
	s.style.display = "block";
	s.style.float= "left";
	s.style.margin = "5px 0px 0px 20px";
	s.style.fontSize = "15px";
	s.style.fontFamily = "Arial, Helvetica, sans-serif";
	s.style.color = "#505050";
	
	a.style.display = "block";
	a.style.float= "left";
	a.style.margin = "5px 0px 0px 5px";
	a.style.height = "100%";
	a.style.fontSize = "15px";
	a.style.fontFamily = "Arial, Helvetica, sans-serif";
	a.style.color = "#505050";
	
	
	a.onmouseover = function(){ this.style.textDecoration = "underline"; this.style.color = "#303030"; };
	a.onmouseout = function(){ this.style.textDecoration = "none"; this.style.color = "#505050"; };
	
	
	
	
	d.appendChild(s);
	d.appendChild(a);
	document.body.appendChild(d);
	setTimeout(function(){d.style.top = "0px";},10);
<?php
}
else if($api == 1)
{
	?>
	{"shorUrl":"http://<?php echo $SERVER_URL; ?>/<?php echo createLink($url); ?>"}
	<?php
}
else
{
	echo 'http://'.$SERVER_URL.'/'.createLink($url);
}


?>